### ISSUE TITLE
Async Client doesnt work properly 

### ISSUE THREAD

**Issue by sureshreddyguntaka** [sureshreddyguntaka/udvi-rpc#1]
Async client is not working properly. When run for the first time it works fine if try to connect again it fails with the following error message

Exception in thread "main" java.lang.RuntimeException: Cann't connect any servers!
    at io.udvi.rpc.common.proxy.BaseObjectProxy.chooseHandler(BaseObjectProxy.java:116)
    at io.udvi.rpc.common.proxy.ObjectProxy.call(ObjectProxy.java:61)
    at io.udvi.rpc.example.async.AsyncHelloClient.main(AsyncHelloClient.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by sureshreddyguntaka** [comment]
This issue is because of the fact that in the example code we are trying to initialize proxy too quickly to solve that problem use pooled client per class.
